# Generated by Django 3.2.6 on 2023-08-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraunts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restraunts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
