# Generated by Django 3.2.6 on 2023-08-10 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restraunts', '0002_alter_restraunts_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restraunts',
            new_name='Restraunt',
        ),
    ]
